### ISSUE TITLE
The HCAP standards seem to often be duplicated in the database. Can we clean that? There's also some with 0 work processes or skills. Can we investigate?

### ISSUE THREAD

**Issue by Pcushing** [WorkHands/RAPiDSkills#125] opened 2019-12-17 22:38 UTC

**Comment by littleforest** [comment] 2019-12-18 20:56
@Pcushing I had mentioned on Slack that there were some records that didn't have any hours noted, but you said that field shouldn't be required since some companies just use it as a placeholder. 

The hcap file is missing skill descriptions  for several blocks -- should I return errors in those cases?

**Comment by Pcushing** [comment] 2019-12-18 21:02
@littleforest sorry. To clarify, i mean 0 work processes or skills. These are the ones i'm looking at with regards to this ticket:

![image](https://user-images.githubusercontent.com/47611/71122831-4edae200-2196-11ea-9e8f-2783854fe3de.png)

It's also a good example of the duplication from the import. 

We'll need to look at those examples that have work processes but no hours. I assumed those had skills but apparently not.

![image](https://user-images.githubusercontent.com/47611/71122983-96616e00-2196-11ea-9607-e7fedab2b3d0.png)

**Comment by littleforest** [comment] 2019-12-18 22:18
@jhash I think some of this is a client-side issue, or I need to figure out a better way to send you the data. I'm returning the list of skill ids in the response - in some cases it's nested under `work_processes`, but in some of these examples above that are missing the skills, it's because there are skills but no work processes.  Here is the example from Pharmacy Support Staff, for example:

```
           "id": "243",
            "type": "occupation_standard",
            "attributes": {
                "title": "Pharmacy Support Staff",
                "organization_title": "River Valley Workforce Institute",
                "occupation_title": "Pharmacy Support Staff",
                "industry_title": null,
                "pdf_filename": null,
                "pdf_url": null,
                "pdf_created_at": null,
                "excel_filename": null,
                "excel_url": null,
                "excel_created_at": null,
                "should_generate_attachments": true
            },
            "relationships": {
                "work_processes": {
                    "data": [],
                    "links": {
                        "self": "http://www.rapidskills.org/api/v1/occupation_standards/243/relationships/work_processes",
                        "related": "http://www.rapidskills.org/api/v1/occupation_standards/243/work_processes"
                    }
                },
                "skills": {
                    "data": [
                        {
                            "id": "6460",
                            "type": "skill"
                        },
                        {
                            "id": "6462",
                            "type": "skill"
                        },
                        {
                            "id": "6464",
                            "type": "skill"
                        },
                        {
                            "id": "6466",
                            "type": "skill"
                        },
                        {
                            "id": "6468",
                            "type": "skill"
                        },
                        {
                            "id": "6470",
                            "type": "skill"
                        },
                        {
                            "id": "6472",
                            "type": "skill"
                        },
                        {
                            "id": "6474",
                            "type": "skill"
                        },
                        {
                            "id": "6476",
                            "type": "skill"
                        },
                        {
                            "id": "6478",
                            "type": "skill"
                        },
                        {
                            "id": "6479",
                            "type": "skill"
                        },
                        {
                            "id": "6482",
                            "type": "skill"
                        },
                        {
                            "id": "6483",
                            "type": "skill"
                        },
                        {
                            "id": "6485",
                            "type": "skill"
                        },
                        {
                            "id": "6487",
                            "type": "skill"
                        },
                        {
                            "id": "6489",
                            "type": "skill"
                        },
                        {
                            "id": "6491",
                            "type": "skill"
                        },
                        {
                            "id": "6493",
                            "type": "skill"
                        },
                        {
                            "id": "6495",
                            "type": "skill"
                        },
                        {
                            "id": "6497",
                            "type": "skill"
                        },
                        {
                            "id": "6499",
                            "type": "skill"
                        },
                        {
                            "id": "6501",
                            "type": "skill"
                        },
                        {
                            "id": "6503",
                            "type": "skill"
                        },
                        {
                            "id": "6505",
                            "type": "skill"
                        },
                        {
                            "id": "6507",
                            "type": "skill"
                        },
                        {
                            "id": "6509",
                            "type": "skill"
                        },
                        {
                            "id": "6511",
                            "type": "skill"
                        },
                        {
                            "id": "6513",
                            "type": "skill"
                        },
                        {
                            "id": "6515",
                            "type": "skill"
                        },
                        {
                            "id": "6517",
                            "type": "skill"
                        },
                        {
                            "id": "6519",
                            "type": "skill"
                        },
                        {
                            "id": "6521",
                            "type": "skill"
                        },
                        {
                            "id": "6523",
                            "type": "skill"
                        },
                        {
                            "id": "6525",
                            "type": "skill"
                        },
                        {
                            "id": "6527",
                            "type": "skill"
                        }
                    ],
                    "links": {
                        "self": "http://www.rapidskills.org/api/v1/occupation_standards/243/relationships/skills",
                        "related": "http://www.rapidskills.org/api/v1/occupation_standards/243/skills"
                    }
                },
                "occupation": {
                    "data": {
                        "id": "252",
                        "type": "occupation"
                    },
                    "links": {
                        "self": "http://www.rapidskills.org/api/v1/occupation_standards/243/relationships/occupation",
                        "related": "http://www.rapidskills.org/api/v1/occupations/252"
                    }
                },
                "organization": {
                    "data": {
                        "id": "111",
                        "type": "organization"
                    },
                    "links": {
                        "self": "http://www.rapidskills.org/api/v1/occupation_standards/243/relationships/organization",
                        "related": "http://www.rapidskills.org/api/v1/organizations/111"
                    }
                }
            },
            "links": {
                "self": "http://www.rapidskills.org/api/v1/occupation_standards/243"
            }
        },
```

**Comment by littleforest** [comment] 2019-12-18 22:21
@jhash Or are you actually counting Work Processes for the "Total Competencies"? Here is the response for CNC Programmer, but it actually has no skills, only work processes:

```
            "id": "252",
            "type": "occupation_standard",
            "attributes": {
                "title": "CNC Programmer",
                "organization_title": "Workforce Intelligence Network (WIN)",
                "occupation_title": "CNC Programmer",
                "industry_title": null,
                "pdf_filename": null,
                "pdf_url": null,
                "pdf_created_at": null,
                "excel_filename": null,
                "excel_url": null,
                "excel_created_at": null,
                "should_generate_attachments": true
            },
            "relationships": {
                "work_processes": {
                    "data": [
                        {
                            "id": "1411",
                            "type": "work_process"
                        },
                        {
                            "id": "1412",
                            "type": "work_process"
                        },
                        {
                            "id": "1413",
                            "type": "work_process"
                        },
                        {
                            "id": "1414",
                            "type": "work_process"
                        },
                        {
                            "id": "1415",
                            "type": "work_process"
                        },
                        {
                            "id": "1416",
                            "type": "work_process"
                        },
                        {
                            "id": "1417",
                            "type": "work_process"
                        },
                        {
                            "id": "1418",
                            "type": "work_process"
                        },
                        {
                            "id": "1419",
                            "type": "work_process"
                        },
                        {
                            "id": "1420",
                            "type": "work_process"
                        },
                        {
                            "id": "1421",
                            "type": "work_process"
                        },
                        {
                            "id": "1422",
                            "type": "work_process"
                        },
                        {
                            "id": "1423",
                            "type": "work_process"
                        },
                        {
                            "id": "1424",
                            "type": "work_process"
                        },
                        {
                            "id": "1425",
                            "type": "work_process"
                        },
                        {
                            "id": "1426",
                            "type": "work_process"
                        },
                        {
                            "id": "1427",
                            "type": "work_process"
                        },
                        {
                            "id": "1428",
                            "type": "work_process"
                        },
                        {
                            "id": "1429",
                            "type": "work_process"
                        },
                        {
                            "id": "1430",
                            "type": "work_process"
                        },
                        {
                            "id": "1431",
                            "type": "work_process"
                        },
                        {
                            "id": "1432",
                            "type": "work_process"
                        },
                        {
                            "id": "1433",
                            "type": "work_process"
                        },
                        {
                            "id": "1434",
                            "type": "work_process"
                        },
                        {
                            "id": "1435",
                            "type": "work_process"
                        },
                        {
                            "id": "1436",
                            "type": "work_process"
                        },
                        {
                            "id": "1437",
                            "type": "work_process"
                        },
                        {
                            "id": "1438",
                            "type": "work_process"
                        }
                    ],
                    "links": {
                        "self": "http://www.rapidskills.org/api/v1/occupation_standards/252/relationships/work_processes",
                        "related": "http://www.rapidskills.org/api/v1/occupation_standards/252/work_processes"
                    }
                },
                "skills": {
                    "data": [],
                    "links": {
                        "self": "http://www.rapidskills.org/api/v1/occupation_standards/252/relationships/skills",
                        "related": "http://www.rapidskills.org/api/v1/occupation_standards/252/skills"
                    }
                },
                "occupation": {
                    "data": {
                        "id": "257",
                        "type": "occupation"
                    },
                    "links": {
                        "self": "http://www.rapidskills.org/api/v1/occupation_standards/252/relationships/occupation",
                        "related": "http://www.rapidskills.org/api/v1/occupations/257"
                    }
                },
                "organization": {
                    "data": {
                        "id": "115",
                        "type": "organization"
                    },
                    "links": {
                        "self": "http://www.rapidskills.org/api/v1/occupation_standards/252/relationships/organization",
                        "related": "http://www.rapidskills.org/api/v1/organizations/115"
                    }
                }
            },
            "links": {
                "self": "http://www.rapidskills.org/api/v1/occupation_standards/252"
            }
        },
```

**Comment by jhash** [comment] 2020-01-17 20:11
@Pcushing @littleforest yeah I am currently only counting skills within workProcesses for whatever reason so I can confirm this is a front end issue

**Comment by littleforest** [comment] 2020-01-22 00:14
@jhash I already fixed the duplication bug - did you fix the client-side issues? That's why I assigned it to you.

**Comment by jhash** [comment] 2020-01-22 00:21
@littleforest I reassigned because I'm seeing duplicate occupations coming back on prod

**Comment by jhash** [comment] 2020-01-22 00:22
Ex. 125 and 126

**Comment by littleforest** [comment] 2020-01-22 00:34
Okay, the bug is fixed, but I didn't clean the duplicates out of production, so I'll leave this open as a reminder.

**Closed** 2020-02-13 17:59 UTC
Labels: bug
